### ISSUE TITLE
Quản lý công dân

### ISSUE THREAD

**Issue by linhtranvu** [linhtranvu/motcua#26]
- Kéo riêng portlet công dân ra thành menu riêng, không trỏ về cái 1 cửa cũ như hiện nay
- Sửa link chỗ không tìm thấy công dân về link mới này, có target = _blank để mở cửa sổ mới

![image](https://user-images.githubusercontent.com/1935451/43567364-b789b5aa-965b-11e8-8a97-41b011deceeb.png)

**Comment by huuthanh3108** [comment]
Đã xử lý xong issues này

**Comment by letronglinh1991** [comment]
Đã hoàn tất issue này
