### ISSUE TITLE
Hồ sơ theo quy trình một bước

### ISSUE THREAD

**Issue by linhtranvu** [linhtranvu/motcua#33]
Theo quy trình của 1 cửa cũ thì hồ sơ một bước thì sau khi một cửa nhận hồ sơ là hoàn thành.

Hiện nay quy trình chưa cấu hình được việc này mà vẫn cần công chức một cửa bấm hoàn thành

**Comment by letronglinh1991** [comment]
Đã code xong quy trình 1 bước.
