### ISSUE TITLE
Triển khai Sở Công Thương

### ISSUE THREAD

**Issue by linhtranvu** [linhtranvu/motcua#34]
Để triển khai Sở Công Thương cần thực hiện các việc sau:

1. Quy trình 1 bước https://github.com/linhtranvu/motcua/issues/33
2. Kiểm tra Ứng dụng của SCT để map auto hồ sơ giữa 2 bên cho đúng (nếu không sửa code)

**Comment by letronglinh1991** [comment]
Đã xử lý, chờ feedback từ tester .
