### ISSUE TITLE
Dòng luân chuyển của hồ sơ 1 cửa tại UBND TP

### ISSUE THREAD

**Issue by linhtranvu** [linhtranvu/motcua#36]
Hiện tại hồ sơ 1 cửa tại UBND TP ở hệ thống riêng nên không có dòng luân chuyển, các cách để tìm dòng luân chuyển.

1. Tìm văn bản đến tại UBND TP thông qua số ký hiệu (nhớ dùng post, get sẽ lỗi font)

https://egov.danang.gov.vn/widget/ttqlvbdh?p_p_id=thongtinvanbanchitietmanagement_WAR_qlvbdhappportlet&p_p_lifecycle=1&p_p_state=exclusive&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_thongtinvanbanchitietmanagement_WAR_qlvbdhappportlet_javax.portlet.action=getDanhSachVanBanDenEx&userName=73&password=d41d8cd98f00b204e9800998ecf8427e&type=001&idDonVi=73&soKyHieu=01/TTr-CCVTLT

2. JSON trả về có id, ví dụ trên là 7961062, gọi WS để lấy quá trình xử lý dựa vào ID

https://egov.danang.gov.vn/widget/ttqlvbdh?p_p_id=thongtinvanbanchitietmanagement_WAR_qlvbdhappportlet&p_p_lifecycle=1&p_p_state=exclusive&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_thongtinvanbanchitietmanagement_WAR_qlvbdhappportlet_javax.portlet.action=getQuaTrinhXuly&userName=73&password=d41d8cd98f00b204e9800998ecf8427e&idVanban=7961062

3. Vẽ ra giao diện quá trình xử lý từ json trả về, 1 dòng dữ liệu gồm:

Ngày chuyển, Người gửi, Phòng người gửi, Người nhận, Phòng người nhận, Nội dung

**Comment by letronglinh1991** [comment]
đã hoàn thành. chờ phản hồi từ tester.
