### ISSUE TITLE
Thêm Mã hồ sơ ở tên trích yếu chuyển ban hành

### ISSUE THREAD

**Issue by linhtranvu** [linhtranvu/motcua#43]
Khi gọi WS chuyển ban hành, trong trích yếu của hồ sơ bổ sung thêm Mã hồ sơ để có thể truy ngược lại hồ sơ khi cần thiết. Hiện nay danh sách chờ ban hành nhiều đơn vị rất rối

**Comment by letronglinh1991** [comment]
đã fix - code đã deploy lên QA
