### ISSUE TITLE
Không có ngày hoàn thành khi Bổ sung, Hồ sơ không xử lý được với hs liên thông

### ISSUE THREAD

**Issue by linhtranvu** [linhtranvu/motcua#44]
Hiện model kết thúc hồ sơ sai, nếu hồ sơ có liên thông mà sử dụng nút bổ sung hồ sơ, Hồ sơ k xử lý được thì chỉ update ngày Hoàn thành nội bộ, trong khi trường hợp này phải Update cả ngày hoàn thành hồ sơ.

**Comment by letronglinh1991** [comment]
Đã fix, deploy code lên QA.
